export const ScrollData = [{
        id: 1,
        to: 'about',
        title: 'About',
        smooth: true,
        duration: 500,
        spy: true,
        exact: 'true',
        offset: -80,
    },

    {
        id: 2,
        to: 'discover',
        title: 'Discover',
        smooth: true,
        duration: 500,
        spy: true,
        exact: 'true',
        offset: -80,
    },
    {
        id: 3,
        to: 'services',
        title: 'Services',
        smooth: true,
        duration: 500,
        spy: true,
        exact: 'true',
        offset: -80,
    },
    {
        id: 4,
        to: 'signup',
        title: 'Sign Up',
        smooth: true,
        duration: 500,
        spy: true,
        exact: 'true',
        offset: -80,
    },
];